name: $(Build.BuildId)

# Triggers Pipeline only from schedule
trigger: none

# Run a daily test at midnight
schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight test
    branches:
      include:
        - master

# Define resources for container to use
resources:
  containers:
    - container: prime
      image: dfdsdk/prime-pipeline:0.3.13
      env:
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)

# Define variable group to use
variables:
  - group: "Infrastructure-Modules QA"

stages:
  # Continuous Integration steps
  - stage: CI
    displayName: "Continuous Integration"
    pool:
      vmImage: "ubuntu-latest"

    jobs:
      - job: init_shared
        displayName: Init EKS shared resources
        container: prime
        steps:
          - bash: ./src/qa-test-eks.sh apply-all _global/eks-public-s3-bucket
            displayName: "Provision public EKS S3 bucket"

      - job: eks_1_13
        displayName: EKS 1.13
        container: prime
        dependsOn: init_shared
        steps:
          - bash: ./src/qa-test-eks.sh init
            displayName: "Init"
            # condition: succeeded()
          - bash: ./src/qa-test-eks.sh plan k8s-qa13/cluster
            displayName: "Run Terraform Plan"
            # condition: succeeded()
          - bash: ./src/qa-test-eks.sh apply-all k8s-qa13
            displayName: "Run Terraform Apply"
            # condition: succeeded()
          - bash: ./src/qa-test-eks.sh test k8s-qa13
            displayName: "Run tests"
            # condition: succeeded()
          - bash: ./src/qa-test-eks.sh destroy-all k8s-qa13
            displayName: "Run Terraform Destroy"
            condition: always()

      - job: eks_1_14
        displayName: EKS 1.14
        container: prime
        dependsOn: init_shared
        steps:
          - bash: ./src/qa-test-eks.sh init
            displayName: "Init"
            # condition: succeeded()
          - bash: ./src/qa-test-eks.sh plan k8s-qa14/cluster
            displayName: "Run Terraform Plan"
            # condition: succeeded()
          - bash: ./src/qa-test-eks.sh apply-all k8s-qa14
            displayName: "Run Terraform Apply"
            # condition: succeeded()
          - bash: ./src/qa-test-eks.sh test k8s-qa14
            displayName: "Run tests"
            # condition: succeeded()
          - bash: ./src/qa-test-eks.sh destroy k8s-qa14
            displayName: "Run Terraform Destroy"
            condition: always()

      - job: destroy_shared
        displayName: Destroy EKS shared resources
        container: prime
        dependsOn:
          - eks_1_13
          - eks_1_14
        # condition: always()
        steps:
          - bash: ./src/qa-test-eks.sh destroy-all _global/eks-public-s3-bucket
            displayName: "Destroy public EKS S3 bucket"
