trigger: none

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight test
  branches:
    include:
    - master

pool:
  name: Docker-pool

resources:
   containers:
     - container: pre_prime
       image: dfdsdk/prime-pipeline:0.3.12
       env:
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

container: qa
variables:
- group: QA
steps:
- bash: 
    ./src/qa-pipeline.sh
  displayName: Integration test against QA
