name: $(Build.BuildId)

# Triggers Pipeline only from schedule
trigger: none

# Run a daily test at midnight
schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight test
    branches:
      include:
        - master

# Define resources for container to use
resources:
  containers:
    - container: prime
      image: dfdsdk/prime-pipeline:0.3.13
      env:
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)

# Define variable group to use
variables:
  - group: "Infrastructure-Modules QA"

stages:
  # Continuous Integration steps
  - stage: CI
    displayName: "Continuous Integration"
    pool:
      vmImage: "ubuntu-latest"

    jobs:
      - job: eks_1_13
        displayName: EKS 1.13
        container: prime
        steps:
          - bash: ./src/qa-test-eks.sh init
            displayName: "Init"
            # condition: succeeded()
          - bash: ./src/qa-test-eks.sh plan
            displayName: "Run Terraform Plan"
            # condition: succeeded()
          - bash: ./src/qa-test-eks.sh apply
            displayName: "Run Terraform Apply"
            # condition: succeeded()
          - bash: ./src/qa-test-eks.sh test
            displayName: "Run tests"
            # condition: succeeded()
          - bash: ./src/qa-test-eks.sh destroy
            displayName: "Run Terraform Destroy"
            condition: always()
